### ISSUE TITLE
Build doesn't produce `.so` on Linux 64 bits

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaOpt/COINMetisBuilder#1]
Using with BinaryProvider fails because no `.so` is produced.

**Comment by juan-pablo-vielma** [comment]
The dynamic version is released under tag `v1.3.5-1`, so you can use it directly from BinaryProvider by setting `bin_prefix = "https://github.com/JuliaOpt/COINMetisBuilder/releases/download/v1.3.5-1/build_COINMetisBuilder.v1.3.5.jl"` Let me know if this doesn't work. 

I will leave this issue open (even if the comments above work) to remind me to release both versions for future updates (the static `vxxx-x-static` and the dynamic `vxxx-x`).

**Comment by abelsiqueira** [comment]
Thanks, @juan-pablo-vielma, completely missed the release below.
